[relaychain]

default_command = "../polkadot-sdk/target/release/polkadot"

chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2000
cumulus_based = true

[[parachains.collator]]
name = "parachain-A-2000-collators1"
command = "./target/release/parachain-template-node"

[[parachains]]
id = 2001
cumulus_based = true

[[parachains.collator]]
name = "parachain-B-2001-collators1"
command = "./target/release/parachain-template-node"
